#!/usr/bin/env python
from socketserver import (TCPServer as TCP, StreamRequestHandler as SRH)
from time import ctime

host = ''
prot = 21567
addr = (host,prot)

class MyRequestHandler(SRH):
    def handle(self):
        print('....connected from :,' + self.client_address)
        self.wfile.write('[%s] %s' % (ctime(),self.rfile.readline()))

S = TCP(addr,MyRequestHandler)
print('waiting for connection...')
S.serve_forever()



